### ISSUE TITLE
Assess upgradeability of packaged Electron apps

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#172]
Ideally, people who install the Sheikah prototype should not need to download future releases. The app itself should self-upgrade. In the early days, we may even want to make this process happen automatically so that no one is left behind with broken old releases.

**Comment by mariocao** [comment]
Source: https://github.com/electron/electron/blob/master/docs/api/auto-updater.md
> Currently, **only macOS and Windows are supported**. There is no built-in support for auto-updater on Linux, so it is recommended to use the distribution's package manager to update your app.

**Comment by mariocao** [comment]
I will take a look to this project: [electron-simple-updater](https://github.com/megahertz/electron-simple-updater)

**Comment by csmoe** [comment]
It seems the more popular [electron-builder](https://github.com/electron-userland/electron-builder) provides the built-in [auto-update](https://www.electron.build/auto-update) function.

**Comment by mariocao** [comment]
[electron-biulder](https://github.com/electron-userland/electron-builder) has *electron-updater* package and it seems to works fine. I did some tests and it works for Linux. However, I encountered some problems while running AppImage due to an open issue ([#2958](https://github.com/electron-userland/electron-builder/issues/2958)). The temporary workaround was to downgrade electron-builder to a previous version (e.g. 20.13.3).

**Comment by mariocao** [comment]
Btw, playing around with `electron-builder`, it seems that the default behaviour is to delete the old version of the app. For that reason, if there is no version tag in the file name (by default there is), then it will be as replacing the previous version by the new one. :smiley:.  In other words, despite there might be some configuration to be done, the upgradeability using `electron-builder` seems quite good.
