### ISSUE TITLE
build(ts): add TS compiler option: strictPropertyInitialization

### ISSUE THREAD

**Issue by anler** [witnet/sheikah#234]
Currently, we allow this kind of behaviour in our codebase:
```typescript
class User {
    username: string;
}

const user = new User();

// Runtime TypeError: Cannot read property 'toLowerCase' of undefined
const username = user.username.toLowerCase();
```

TypeScript should guard us against having uninitialized properties in classes or to annotate those accordingly with `| undefined`, and that's what `--strictPropertyInitialization` is for, with it, the code above wouldn't compile:

```typescript
class User {
    // Type error: Property 'username' has no initializer
    // and is not definitely assigned in the constructor
    username: string;
}
```

More info at [Marius Schulz's blog](https://blog.mariusschulz.com/2018/05/20/typescript-2-7-strict-property-initialization)

**Comment by aesedepece** [comment]
Enabling this flag is perfectly fine by me if the behavior is exactly as described by @mariusschulz in [his blog entry][schulz]:

*"If a class property neither has an explicit initializer nor a type including undefined, the type checker requires that property to be initialized directly within the constructor; otherwise, strict property initialization checks will fail."*

I mean, the compiler should be OK with properties that are deterministically initialized in the main branch of the class constructor.

As long as that's the case, I think that enabling this flag is totally desirable. Moreover, I'm not aware at this time of any part of our code base that would be broken by this stricter policy.

:green_heart: 

[schulz]: https://blog.mariusschulz.com/2018/05/20/typescript-2-7-strict-property-initialization
