### ISSUE TITLE
Add ability to export private keys

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/sheikah#932]
As a node operator, I want to import an address generated in sheikah into the node, and have all the mined wits magically appear in a user friendly interface.

The exported private key should be compatible with the node `importPrivateKey` method, which does not exist yet but it will probably accept a private key serialized in hex.

**Comment by aesedepece** [comment]
Private keys are expected to be imported / exported using the exchange
format called
SLIP32:
https://github.com/satoshilabs/slips/blob/master/slip-0032.md

Regarding the user story, I don't think this feature enables interoperation
of wallets between Sheikah and the node. In the first place because they
derive keys differently and in the second because of UI/UX challenges.

**Comment by Tommytrg** [comment]
Currently, a user can export their private key as xprv. This was added in #1508
